# >>>TODO: this needs tunning

# waypoint_A: [2.0,-1.0,1.0]
# waypoint_B: [0.0,0.0,1.0]
# waypoint_C: [0.0,1.0,1.0]
waypoint_A: [-3.98,-1.99,1.0]
waypoint_A_1: [1.0,0.0,1.0]
waypoint_B: [-3.83,-8.88,1.0]
waypoint_C: [-1.19,-12.0,1.0]
waypoint_C_1: [0.0,-12.0,1.0]
waypoint_C_2: [0.0,0.0,1.0]
target_pose: [0.4, -0.3, 0.26, -0.011, 1.57, 0.037]